name: package cleanup
on:
  push:

jobs:
  fail_purging_semantic:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          organization: armbian
          type: container
          keep: 0
          names: |
            root
