name: Rootfs
on:
  workflow_dispatch:
  workflow_call:

jobs:

  Minimal:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/generate.yml
    secrets: inherit

    with:

      minimal: 'yes'
      desktop: 'no'
      variant: ''

  Server:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/generate.yml

    with:

      minimal: 'no'
      desktop: 'no'
      variant: ''
