name: Rootfs
on:
  workflow_dispatch:
  workflow_call:

jobs:

  MIN:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: ./.github/workflows/script.yml
    secrets: inherit

    with:

      minimal: 'yes'
      desktop: 'no'
      variant: ''
